from django.urls import path
from .views import (
    TeamListView,
    SpaceListView,
    SpaceAvailabilityView,
    SpaceReservationListView,
    ReservationListCreateView,
    ReservationTicketView,
    ReservationPublicCancelView,
    AdminLoginView,
    AdminReservationListView,
    AdminReservationCancelView,
    AdminReservationDeleteView,
    AdminTeamListCreateView,
    AdminTeamDetailView,
    AdminBuildingListCreateView,
    AdminBuildingDetailView,
    AdminSpaceListCreateView,
    AdminSpaceDetailView,
    AdminReservationStatusView,
)

urlpatterns = [
    path("teams/",                                     TeamListView.as_view()),
    path("spaces/",                                    SpaceListView.as_view()),
    path("spaces/availability/",                       SpaceAvailabilityView.as_view()),
    path("spaces/<int:pk>/reservations/",              SpaceReservationListView.as_view()),
    path("reservations/",                              ReservationListCreateView.as_view()),
    path("reservations/<int:pk>/ticket/",              ReservationTicketView.as_view()),
    path("reservations/<int:pk>/cancel/",              ReservationPublicCancelView.as_view()),
    path("admin/login/",                               AdminLoginView.as_view()),
    path("admin/teams/",                               AdminTeamListCreateView.as_view()),
    path("admin/teams/<int:pk>/",                      AdminTeamDetailView.as_view()),
    path("admin/buildings/",                           AdminBuildingListCreateView.as_view()),
    path("admin/buildings/<int:pk>/",                  AdminBuildingDetailView.as_view()),
    path("admin/spaces/",                              AdminSpaceListCreateView.as_view()),
    path("admin/spaces/<int:pk>/",                     AdminSpaceDetailView.as_view()),
    path("admin/reservations/",                        AdminReservationListView.as_view()),
    path("admin/reservations/<int:pk>/cancel/",        AdminReservationCancelView.as_view()),
    path("admin/reservations/<int:pk>/status/",        AdminReservationStatusView.as_view()),
    path("admin/reservations/<int:pk>/",               AdminReservationDeleteView.as_view()),
]
